### ISSUE TITLE
Discuss easy access to to facets in query:

### ISSUE THREAD

**Issue by kaystrobach** [kaystrobach/FLOW.VisualSearch#13]
Idea, have default values, when a facet is not selected, very useable to hide non active records by default. Maybe add this directly in the config at the end

From the config:

```yaml
      hidden:
        label: "Versteckte"
        selector:
          conditions:
            once: true
          values:
            show: zeigen
        matches: []
```

From the searchable repo

```php
protected function initializeFindByQuery($queryObject, $searchName)
    {
        if ($searchName !== 'FourViewture\KIS\CRM\Domain\Model\Lead') {
            return [];
        }

        $facets = $this->queryStorage->getQuery($searchName)->getFacets();
        $hasHiddenFacet = false;
        foreach ($facets as $facet) {
            if (($facet instanceof Facet) && ($facet->getFacet() === 'hidden')) {
                $hasHiddenFacet = true;
                break;
            }
        }

        if (!$hasHiddenFacet) {
            return [
                $queryObject->equals('hidden.hidden', 0)
            ];
        }

        return [];
    }
```
